### ISSUE TITLE
Additional System Support?

### ISSUE THREAD

**Issue by sirkerry** [mybigfriendjo/actor-attribute-list#2]
Would it be possible to add support for Savage Worlds (swade), Old School Essentials (ose), and Worlds Without Number (wwn) game systems?

**Comment by mybigfriendjo** [comment]
old school essentials seem to not enrich their descriptions - which might make it a bit of a moot point to include. see issue #1 
i can take a look at the other two - will have to wait until at least next weekend though.

**Comment by mybigfriendjo** [comment]
i have added all 3 systems with v0.2.0. version is up on the package repository (https://foundryvtt.com/packages/actor-attribute-list) and tested with v11 and v12 (where applicable - ose and swade are not on v12 yet)
though for old school essentials and worlds without number the enrichments are missing. so while the module will show attributes they won't be usable for inline rolls in descriptions.

**Comment by mybigfriendjo** [comment]
systems added. issue closed
